export interface UserStory {
  name: string;
  role: string;
  location: string;
  avatar: string;
  color: string;
  borderColor: string;
  bgColor: string;
  problem: string;
  solution: string;
  quote: string;
  tags: string[];
}

export const userStories: UserStory[] = [
  {
    name: "Aynur",
    role: "Quantitative Researcher",
    location: "London",
    avatar: "/avatars/aynur.png",
    color: "from-sky-500 to-blue-500",
    borderColor: "border-sky-500/30",
    bgColor: "bg-sky-500/10",
    problem: "Wants to build an intelligent trading bot using neuro-symbolic AI. But all the literature is scattered across papers about visual reasoning and medical diagnosis — nothing about finance and LLMs.",
    solution: "A book that covers neuro-symbolic AI specifically through the lens of quantitative finance, with examples using market data, and deep dives into LLM integration for trading strategies.",
    quote: "Finally, a resource that speaks my language — literally about MY use case.",
    tags: ["Neuro-symbolic AI", "Finance", "LLM Integration"],
  },
  {
    name: "Marina",
    role: "Fighting for her life",
    location: "São Paulo",
    avatar: "/avatars/marina.png",
    color: "from-amber-500 to-orange-500",
    borderColor: "border-amber-500/30",
    bgColor: "bg-amber-500/10",
    problem: "Diagnosed with stage 4 pancreatic cancer. 3% survival rate with standard treatment. She wants to understand cutting-edge research on innovative treatments and supplements — but papers are impenetrable and she has no time.",
    solution: "A comprehensive, accessible guide synthesizing the latest research on emerging treatments, clinical trials, and evidence-based supplements — written in plain language she can actually understand.",
    quote: "Knowledge is power. This gave me hope and a plan to discuss with my doctors.",
    tags: ["Oncology Research", "Accessible Language", "Life-saving"],
  },
  {
    name: "James",
    role: "Career Changer",
    location: "Detroit",
    avatar: "/avatars/james.png",
    color: "from-slate-500 to-zinc-600",
    borderColor: "border-slate-500/30",
    bgColor: "bg-slate-500/10",
    problem: "Lost his manufacturing job after 28 years. Trying to transition to tech but every bootcamp assumes you're young, have endless time, and already speak tech. He has mechanical intuition, not coding intuition.",
    solution: "Programming fundamentals explained for someone who thinks in physical systems — variables as containers, functions as assembly lines, debugging as troubleshooting. His experience is an asset, not a liability.",
    quote: "I built cars for 28 years. They said I couldn't learn to build software. Watch me.",
    tags: ["Career Change", "Practical Approach", "No Assumptions"],
  },
  {
    name: "Amir",
    role: "Gifted Student",
    location: "Dhaka, Bangladesh",
    avatar: "/avatars/amir.png",
    color: "from-amber-500 to-orange-500",
    borderColor: "border-amber-500/30",
    bgColor: "bg-amber-500/10",
    problem: "Mathematically gifted and dreams of cutting-edge research. But no access to elite institutions, world-class labs, or expensive resources. Also struggles with English-language materials.",
    solution: "Advanced mathematics and ML textbooks in Bangla, starting exactly where he is, building toward research-level understanding — unlocking his potential without geographic or financial barriers.",
    quote: "The best education in my language. I can finally reach my potential.",
    tags: ["Native Language", "Advanced Math", "Democratized Access"],
  },
  {
    name: "Marcus",
    role: "Dyslexic Entrepreneur",
    location: "Austin",
    avatar: "/avatars/marcus.png",
    color: "from-cyan-500 to-sky-600",
    borderColor: "border-cyan-500/30",
    bgColor: "bg-cyan-500/10",
    problem: "Brilliant business mind but traditional textbooks are torture. Dense walls of text make learning new skills — marketing analytics, finance — nearly impossible. He's built companies but can't read a textbook.",
    solution: "Concepts broken into digestible chunks, heavy use of diagrams and analogies, structured for how his brain actually works. Business knowledge without the wall-of-text barrier.",
    quote: "I've built a company. But I still can't read a textbook without wanting to throw it across the room.",
    tags: ["Dyslexia-Friendly", "Visual Learning", "Business"],
  },
  {
    name: "Priya",
    role: "Climate Journalist",
    location: "Mumbai",
    avatar: "/avatars/priya.png",
    color: "from-green-500 to-emerald-600",
    borderColor: "border-green-500/30",
    bgColor: "bg-green-500/10",
    problem: "Needs to understand complex climate science, economics, and policy to write accurate stories. She's not a scientist — she's a storyteller who needs to get it right. Millions read what she writes.",
    solution: "Climate science distilled for a smart non-scientist — the physics, the economics, the politics, with India-specific context and guidance on communicating findings accurately.",
    quote: "Millions read what I write. I can't afford to get the science wrong.",
    tags: ["Climate Science", "Journalism", "India Context"],
  },
  {
    name: "Anna",
    role: "Computational Biologist",
    location: "Boston",
    avatar: "/avatars/anna.png",
    color: "from-emerald-500 to-teal-500",
    borderColor: "border-emerald-500/30",
    bgColor: "bg-emerald-500/10",
    problem: "Needs to learn Python for work, but generic tutorials use boring examples about calculators and todo apps. She falls asleep. Nothing connects to what she actually does.",
    solution: "A hands-on Python book where every example analyzes genomic data, processes protein sequences, and visualizes biological pathways — her actual work.",
    quote: "I learned more in one week than three months of generic courses.",
    tags: ["Python", "Bioinformatics", "Hands-on"],
  },
  {
    name: "Sofia",
    role: "First-Gen College Student",
    location: "Phoenix",
    avatar: "/avatars/sofia.png",
    color: "from-orange-500 to-amber-600",
    borderColor: "border-orange-500/30",
    bgColor: "bg-orange-500/10",
    problem: "First in her family to attend university. No one at home can explain organic chemistry or academic writing. Tutoring is expensive. She feels like everyone else got a secret manual she never received.",
    solution: "Organic chemistry with extra scaffolding — explains the 'obvious' things professors assume you know, with study strategies built in, written like a patient mentor who remembers what it's like to struggle.",
    quote: "Everyone else seems to just... know things. I'm always three steps behind.",
    tags: ["First-Generation", "Extra Support", "Mentorship"],
  },
  {
    name: "Kofi",
    role: "Small Business Owner",
    location: "Accra, Ghana",
    avatar: "/avatars/kofi.png",
    color: "from-yellow-500 to-amber-600",
    borderColor: "border-yellow-500/30",
    bgColor: "bg-yellow-500/10",
    problem: "Runs a successful tailoring business, wants to expand online. But every e-commerce guide assumes US/EU payment systems, logistics, and infrastructure. None of it applies to his reality.",
    solution: "E-commerce and digital marketing for West African markets — mobile money integration, local logistics solutions, WhatsApp and Facebook selling strategies that actually work in Ghana.",
    quote: "The internet was supposed to level the playing field. But all the playbooks are written for Silicon Valley.",
    tags: ["African Markets", "E-commerce", "Local Context"],
  },
  {
    name: "Rachel",
    role: "Living with Chronic Fatigue",
    location: "Melbourne",
    avatar: "/avatars/rachel.png",
    color: "from-teal-500 to-cyan-600",
    borderColor: "border-teal-500/30",
    bgColor: "bg-teal-500/10",
    problem: "Brilliant mind but can only focus for 20-30 minutes before crashing. Traditional courses assume 3-hour study sessions. She wants to learn UX design but every resource is built for people with unlimited energy.",
    solution: "UX design in micro-chapters — each self-contained, with clear stopping points and recaps. Designed for interrupted learning. Progress even on bad days.",
    quote: "My brain works fine. It's my body that won't cooperate. Why does every course assume unlimited energy?",
    tags: ["Chronic Illness", "Micro-Learning", "Accessible Pace"],
  },
  {
    name: "David",
    role: "Deaf Entrepreneur",
    location: "London",
    avatar: "/avatars/david.png",
    color: "from-sky-500 to-blue-600",
    borderColor: "border-sky-500/30",
    bgColor: "bg-sky-500/10",
    problem: "Most learning content is video-based now. YouTube tutorials, online courses — all assume you can hear. Auto-generated captions are garbage. He's been excluded from the learning economy.",
    solution: "Comprehensive written content with detailed visual diagrams. Everything a video would teach, in a format he can actually use. No dependence on audio explanations.",
    quote: "The shift to video killed my ability to self-educate. Everyone forgot people like me exist.",
    tags: ["Deaf Accessible", "Visual-First", "Written Content"],
  },
  {
    name: "Mira",
    role: "Accounting Student",
    location: "Toronto",
    avatar: "/avatars/mira.png",
    color: "from-cyan-500 to-blue-500",
    borderColor: "border-cyan-500/30",
    bgColor: "bg-cyan-500/10",
    problem: "Has to pass her CPA exam but the material is soul-crushingly dry. She's falling behind because she can't stay engaged with traditional textbooks.",
    solution: "An accounting prep book with Rick and Morty-style humor woven throughout. Debits and credits explained through interdimensional adventures. Actually fun to read.",
    quote: "I never thought I'd laugh while studying depreciation methods. Wubba lubba dub dub!",
    tags: ["Accounting", "Rick & Morty Style", "Actually Fun"],
  },
];
